$axure.loadCurrentPage({
  "url":"文件兼容.html",
  "generationDate":new Date(1462772421414.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd4576a0bda746da8f5207f49b2669d3",
    "type":"Axure:Page",
    "name":"文件兼容",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3c75b342abf4b5d937806370e1f525c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":21},
            "size":{
              "width":600,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ec714b5a2744db9c3bf853d5fadfd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":21},
                "size":{
                  "width":600,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u0.png"}},
{
          "id":"80e2e16ec6ca480486ff7046fce73e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF264655},
            "location":{
              "x":127,
              "y":510},
            "size":{
              "width":595,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c518b343a9841bca1705229caecce99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF264655},
                "location":{
                  "x":127,
                  "y":510},
                "size":{
                  "width":595,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u2.png"}},
{
          "id":"448c9aee1bab456cb0b098fa6fde6cd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00B5FA},
            "location":{
              "x":190,
              "y":76},
            "size":{
              "width":122,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f25f1d1187b641f3a1b8daad981f7264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00B5FA},
                "location":{
                  "x":190,
                  "y":76},
                "size":{
                  "width":122,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u4.png"}},
{
          "id":"c68fccd86d8644f6bf0461560d644370",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":240},
            "size":{
              "width":410,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e93e652aa3d4d1d9831f6e752edc569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":240},
                "size":{
                  "width":410,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u6.png"}},
{
          "id":"c4ed87a6fff0429ba8715246b42ad998",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9CD5FF,
              "opacity":1},
            "location":{
              "x":217,
              "y":248},
            "size":{
              "width":203,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3c4c6d5ef242ea83265b8cc866fc3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9CD5FF,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":248},
                "size":{
                  "width":203,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u8.png"}},
{
          "id":"ac200b8124f24e2eb59061f72e393804",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":312},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc074f6cd7494563a1e80bbc4a6aacbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":312},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"49a691c1af6a41e792a0978cab830f7d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":338},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3836f839b91949c99f4cbeb9980cea79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":338},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fa5bcb0456694f52b42cebb2f2ee93bb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":364},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18180adbe2c545c09e6801694d7ed2c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":364},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"82a72c90ed284409bb478e5a6ff53e26",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":312},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd599c42d8a94ca38a78a7d7e864c55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":312},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5e8ae23d6c4d4bb2b53e1fe802abaff5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":338},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb8c069ca384e899708c50b0634912c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":338},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5d2061a357b345efb7a231e63fb96098",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":364},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32fb74f3160477996025bc10eb2ed4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":364},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ef083efed20b42eaa774d0baab3bfe28",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":312},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac1471a04334b34a25e46ca99434021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":312},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b15d96f052814f2587f40200d2494f72",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":338},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2741bfcb6db41b3bf07f3463cd3754d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":338},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"24e1ddfc7dd64f1a8bc0d11ecad19a8f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":364},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc9b65c001094d199072f353523f06ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":364},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"327213c39ae4423d833e5b2c6b434cef",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":312},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63716b1dde4a4673b40e7e11998899af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":505,
                  "y":312},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6742a7b06e7e4515ac08d33e0240ddb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF15000},
            "location":{
              "x":236,
              "y":453},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af149eb9a4f4b95be4bd46db69dab79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF15000},
                "location":{
                  "x":236,
                  "y":453},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u30.png"}},
{
          "id":"66eae77430b041e380ae62828da7d4d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEBEBEB},
            "location":{
              "x":360,
              "y":440},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325a6a6364fd4a3a91a1d01c67a540b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEBEBEB},
                "location":{
                  "x":360,
                  "y":440},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u32.png"}},
{
          "id":"372ccc9fd2aa40a4b2a6abb9572ec2fd",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":220,
              "y":190},
            "size":{
              "width":410,
              "height":40},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f524103f6044ab975e12b8371d079c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":220,
                  "y":190},
                "size":{
                  "width":410,
                  "height":40},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u4.png"}},
{
          "id":"60484c44e36b4cac8f7955ff6de0c5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":190},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf17682f1c9141a4a86335d0fea819c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["372ccc9fd2aa40a4b2a6abb9572ec2fd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c87d507d5194fab884895fa34dc2916",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":435},
            "size":{
              "width":130,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"974660350e5a4c3789f8195707abbc22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":435},
                "size":{
                  "width":130,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["c902d0f122674055bb11b989786bea5f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fdf3649ed8564e00b004e453a360374c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["80a78b29eeb849bd8610e1c5c7d8867d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8998d25bce7746c7b94d30253213c4d1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4a7898ca4b55471a8b6d9cfe9597a53b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c902d0f122674055bb11b989786bea5f",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":242,
              "y":167},
            "size":{
              "width":365,
              "height":223},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c511f642b14ae19fbb91b950fe790e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":242,
                  "y":167},
                "size":{
                  "width":365,
                  "height":223},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u16.png"}},
{
          "id":"fdf3649ed8564e00b004e453a360374c",
          "label":"2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":260,
              "y":239},
            "size":{
              "width":310,
              "height":81},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e4046dc820489091d814530befa26f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":260,
                  "y":239},
                "size":{
                  "width":310,
                  "height":81},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/2_u18.png"}},
{
          "id":"80a78b29eeb849bd8610e1c5c7d8867d",
          "label":"3",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":340},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42bc2ca769da451490d41ce204e6b599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":340},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件生成中",
                      "target":{
                        "targetType":"page",
                        "url":"文件生成中.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8998d25bce7746c7b94d30253213c4d1",
          "label":"4",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":392,
              "y":349},
            "size":{
              "width":68,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad9c58eb0e674b58a080e54dc89f3b53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":392,
                  "y":349},
                "size":{
                  "width":68,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["c902d0f122674055bb11b989786bea5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fdf3649ed8564e00b004e453a360374c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["80a78b29eeb849bd8610e1c5c7d8867d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8998d25bce7746c7b94d30253213c4d1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4a7898ca4b55471a8b6d9cfe9597a53b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a7898ca4b55471a8b6d9cfe9597a53b",
          "label":"5",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":550,
              "y":183},
            "size":{
              "width":50,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2773da7e3d114adb942ebca82a6fc877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":550,
                  "y":183},
                "size":{
                  "width":50,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["c902d0f122674055bb11b989786bea5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fdf3649ed8564e00b004e453a360374c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["80a78b29eeb849bd8610e1c5c7d8867d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8998d25bce7746c7b94d30253213c4d1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4a7898ca4b55471a8b6d9cfe9597a53b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a569bb0ad60244b69b60d00b7b964066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF504855},
            "location":{
              "x":514,
              "y":453},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab480ac67dfc4a25a5223c3862200865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF504855},
                "location":{
                  "x":514,
                  "y":453},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u10.png"}},
{
          "id":"48a5fd365d0f415294500e042c5b13e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":437},
            "size":{
              "width":130,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca382218aa5426fba4feb57d70587a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":437},
                "size":{
                  "width":130,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件上传",
                      "target":{
                        "targetType":"page",
                        "url":"文件上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f3c75b342abf4b5d937806370e1f525c":{
      "scriptId":"u0"},
    "e4ec714b5a2744db9c3bf853d5fadfd2":{
      "scriptId":"u1"},
    "80e2e16ec6ca480486ff7046fce73e0f":{
      "scriptId":"u2"},
    "8c518b343a9841bca1705229caecce99":{
      "scriptId":"u3"},
    "448c9aee1bab456cb0b098fa6fde6cd6":{
      "scriptId":"u4"},
    "f25f1d1187b641f3a1b8daad981f7264":{
      "scriptId":"u5"},
    "c68fccd86d8644f6bf0461560d644370":{
      "scriptId":"u6"},
    "2e93e652aa3d4d1d9831f6e752edc569":{
      "scriptId":"u7"},
    "c4ed87a6fff0429ba8715246b42ad998":{
      "scriptId":"u8"},
    "8a3c4c6d5ef242ea83265b8cc866fc3e":{
      "scriptId":"u9"},
    "ac200b8124f24e2eb59061f72e393804":{
      "scriptId":"u10"},
    "fc074f6cd7494563a1e80bbc4a6aacbd":{
      "scriptId":"u11"},
    "49a691c1af6a41e792a0978cab830f7d":{
      "scriptId":"u12"},
    "3836f839b91949c99f4cbeb9980cea79":{
      "scriptId":"u13"},
    "fa5bcb0456694f52b42cebb2f2ee93bb":{
      "scriptId":"u14"},
    "18180adbe2c545c09e6801694d7ed2c8":{
      "scriptId":"u15"},
    "82a72c90ed284409bb478e5a6ff53e26":{
      "scriptId":"u16"},
    "bd599c42d8a94ca38a78a7d7e864c55b":{
      "scriptId":"u17"},
    "5e8ae23d6c4d4bb2b53e1fe802abaff5":{
      "scriptId":"u18"},
    "6fb8c069ca384e899708c50b0634912c":{
      "scriptId":"u19"},
    "5d2061a357b345efb7a231e63fb96098":{
      "scriptId":"u20"},
    "c32fb74f3160477996025bc10eb2ed4d":{
      "scriptId":"u21"},
    "ef083efed20b42eaa774d0baab3bfe28":{
      "scriptId":"u22"},
    "2ac1471a04334b34a25e46ca99434021":{
      "scriptId":"u23"},
    "b15d96f052814f2587f40200d2494f72":{
      "scriptId":"u24"},
    "f2741bfcb6db41b3bf07f3463cd3754d":{
      "scriptId":"u25"},
    "24e1ddfc7dd64f1a8bc0d11ecad19a8f":{
      "scriptId":"u26"},
    "cc9b65c001094d199072f353523f06ff":{
      "scriptId":"u27"},
    "327213c39ae4423d833e5b2c6b434cef":{
      "scriptId":"u28"},
    "63716b1dde4a4673b40e7e11998899af":{
      "scriptId":"u29"},
    "6742a7b06e7e4515ac08d33e0240ddb7":{
      "scriptId":"u30"},
    "3af149eb9a4f4b95be4bd46db69dab79":{
      "scriptId":"u31"},
    "66eae77430b041e380ae62828da7d4d4":{
      "scriptId":"u32"},
    "325a6a6364fd4a3a91a1d01c67a540b8":{
      "scriptId":"u33"},
    "372ccc9fd2aa40a4b2a6abb9572ec2fd":{
      "scriptId":"u34"},
    "78f524103f6044ab975e12b8371d079c":{
      "scriptId":"u35"},
    "60484c44e36b4cac8f7955ff6de0c5a3":{
      "scriptId":"u36"},
    "cf17682f1c9141a4a86335d0fea819c1":{
      "scriptId":"u37"},
    "9c87d507d5194fab884895fa34dc2916":{
      "scriptId":"u38"},
    "974660350e5a4c3789f8195707abbc22":{
      "scriptId":"u39"},
    "c902d0f122674055bb11b989786bea5f":{
      "scriptId":"u40"},
    "32c511f642b14ae19fbb91b950fe790e":{
      "scriptId":"u41"},
    "fdf3649ed8564e00b004e453a360374c":{
      "scriptId":"u42"},
    "28e4046dc820489091d814530befa26f":{
      "scriptId":"u43"},
    "80a78b29eeb849bd8610e1c5c7d8867d":{
      "scriptId":"u44"},
    "42bc2ca769da451490d41ce204e6b599":{
      "scriptId":"u45"},
    "8998d25bce7746c7b94d30253213c4d1":{
      "scriptId":"u46"},
    "ad9c58eb0e674b58a080e54dc89f3b53":{
      "scriptId":"u47"},
    "4a7898ca4b55471a8b6d9cfe9597a53b":{
      "scriptId":"u48"},
    "2773da7e3d114adb942ebca82a6fc877":{
      "scriptId":"u49"},
    "a569bb0ad60244b69b60d00b7b964066":{
      "scriptId":"u50"},
    "ab480ac67dfc4a25a5223c3862200865":{
      "scriptId":"u51"},
    "48a5fd365d0f415294500e042c5b13e6":{
      "scriptId":"u52"},
    "3ca382218aa5426fba4feb57d70587a7":{
      "scriptId":"u53"}}});