$axure.loadCurrentPage({
  "url":"文件生成中.html",
  "generationDate":new Date(1462772421500.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef1aa01fdc824b4bad726de886e65b51",
    "type":"Axure:Page",
    "name":"文件生成中",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ccb3c76996c44c4ad49908c472d0bd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":21},
            "size":{
              "width":600,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50562db161b94f059c53f58cb45d033a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":21},
                "size":{
                  "width":600,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u0.png"}},
{
          "id":"3d2f993ca82e467f85fff2a5c80fa704",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF264655},
            "location":{
              "x":127,
              "y":510},
            "size":{
              "width":595,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1edce9dbc6eb4d11bbe650b761f25dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF264655},
                "location":{
                  "x":127,
                  "y":510},
                "size":{
                  "width":595,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u2.png"}},
{
          "id":"80d4016fd02e4067ac85d3dfe0cfc4f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":130},
            "size":{
              "width":410,
              "height":260},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"968a6318d0e8447ebb778179a512edf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":130},
                "size":{
                  "width":410,
                  "height":260},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件生成中/u4.png"}},
{
          "id":"12f6b0c9f8a14dc3a7525407d03a494a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00B5FA},
            "location":{
              "x":190,
              "y":76},
            "size":{
              "width":122,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e675cfeed964b35ac2c4d35649f4879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00B5FA},
                "location":{
                  "x":190,
                  "y":76},
                "size":{
                  "width":122,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u4.png"}},
{
          "id":"d9e2aa54355348aea93c2c1e9281a00c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":120},
            "size":{
              "width":480,
              "height":301}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3147c4cee1407dab6edc1e8fbeb5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":120},
                "size":{
                  "width":480,
                  "height":301}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件生成中/u8.png"}},
{
          "id":"c51d0b733b4f4185b0101437924eaa26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9EA2AD,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC8CCD7},
            "location":{
              "x":392,
              "y":349},
            "size":{
              "width":200,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc53626e95cc4bb9a59aa0f83671fc38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9EA2AD,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC8CCD7},
                "location":{
                  "x":392,
                  "y":349},
                "size":{
                  "width":200,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件生成中/u10.png"}},
{
          "id":"c405572aebbf4fbb8a1f28a4728a4b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEBEBEB},
            "location":{
              "x":360,
              "y":431},
            "size":{
              "width":140,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d7d7e8bb90438b9ae20ce338578102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEBEBEB},
                "location":{
                  "x":360,
                  "y":431},
                "size":{
                  "width":140,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件生成中/u12.png"}},
{
          "id":"3e0f0f638eb3497cb040a67d9a60915b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF15000},
            "location":{
              "x":236,
              "y":453},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c5212ad0778459b95de1c584f6d46d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF15000},
                "location":{
                  "x":236,
                  "y":453},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u30.png"}},
{
          "id":"8eb088324b124ce397e9a19a1c55506f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":431},
            "size":{
              "width":140,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ca2d3c60704bb7800686f2bd4a0823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":431},
                "size":{
                  "width":140,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9d7072fe9654478fb333308ef6efd0e9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0934fe69ffa541d9a354f9fcb0d332fa"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8df4f3b4e96046e48803f12fda4d3f00"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5c56a71d2f5947ae9139577d50fe13d3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c25634e49ee14a56898692f6bac033f5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a18e76e43ea04abbbcd2a66a4f79f124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":116},
            "size":{
              "width":200,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0b60148a5e7487e9b1789d07597aa43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":116},
                "size":{
                  "width":200,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件生成中/u18.png"}},
{
          "id":"12cfafe919e24a90a84fddbae815dd4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":735,
              "y":116},
            "size":{
              "width":155,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5e7909ca9614fdfb2a57e007f0e801f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":735,
                  "y":116},
                "size":{
                  "width":155,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d7072fe9654478fb333308ef6efd0e9",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":242,
              "y":167},
            "size":{
              "width":365,
              "height":223},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c10cf93c0b4737a5905ccb6cdf10d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":242,
                  "y":167},
                "size":{
                  "width":365,
                  "height":223},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u16.png"}},
{
          "id":"0934fe69ffa541d9a354f9fcb0d332fa",
          "label":"2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":260,
              "y":239},
            "size":{
              "width":310,
              "height":81},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8da640193814048bf3e2c036361dcd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":260,
                  "y":239},
                "size":{
                  "width":310,
                  "height":81},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/2_u18.png"}},
{
          "id":"8df4f3b4e96046e48803f12fda4d3f00",
          "label":"3",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":340},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d82180bc216b4db8847a11e857fd0ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":340},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件兼容",
                      "target":{
                        "targetType":"page",
                        "url":"文件兼容.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c56a71d2f5947ae9139577d50fe13d3",
          "label":"4",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":392,
              "y":349},
            "size":{
              "width":68,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"419402198dec4cc0a88ad79c0e60c877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":392,
                  "y":349},
                "size":{
                  "width":68,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9d7072fe9654478fb333308ef6efd0e9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0934fe69ffa541d9a354f9fcb0d332fa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8df4f3b4e96046e48803f12fda4d3f00"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5c56a71d2f5947ae9139577d50fe13d3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c25634e49ee14a56898692f6bac033f5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c25634e49ee14a56898692f6bac033f5",
          "label":"5",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":550,
              "y":183},
            "size":{
              "width":50,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd11d6dfc6e46158f99df73a49dde09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":550,
                  "y":183},
                "size":{
                  "width":50,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9d7072fe9654478fb333308ef6efd0e9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0934fe69ffa541d9a354f9fcb0d332fa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8df4f3b4e96046e48803f12fda4d3f00"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5c56a71d2f5947ae9139577d50fe13d3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c25634e49ee14a56898692f6bac033f5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ccb3c76996c44c4ad49908c472d0bd4":{
      "scriptId":"u0"},
    "50562db161b94f059c53f58cb45d033a":{
      "scriptId":"u1"},
    "3d2f993ca82e467f85fff2a5c80fa704":{
      "scriptId":"u2"},
    "1edce9dbc6eb4d11bbe650b761f25dac":{
      "scriptId":"u3"},
    "80d4016fd02e4067ac85d3dfe0cfc4f9":{
      "scriptId":"u4"},
    "968a6318d0e8447ebb778179a512edf1":{
      "scriptId":"u5"},
    "12f6b0c9f8a14dc3a7525407d03a494a":{
      "scriptId":"u6"},
    "7e675cfeed964b35ac2c4d35649f4879":{
      "scriptId":"u7"},
    "d9e2aa54355348aea93c2c1e9281a00c":{
      "scriptId":"u8"},
    "4f3147c4cee1407dab6edc1e8fbeb5fd":{
      "scriptId":"u9"},
    "c51d0b733b4f4185b0101437924eaa26":{
      "scriptId":"u10"},
    "dc53626e95cc4bb9a59aa0f83671fc38":{
      "scriptId":"u11"},
    "c405572aebbf4fbb8a1f28a4728a4b3c":{
      "scriptId":"u12"},
    "e8d7d7e8bb90438b9ae20ce338578102":{
      "scriptId":"u13"},
    "3e0f0f638eb3497cb040a67d9a60915b":{
      "scriptId":"u14"},
    "0c5212ad0778459b95de1c584f6d46d1":{
      "scriptId":"u15"},
    "8eb088324b124ce397e9a19a1c55506f":{
      "scriptId":"u16"},
    "40ca2d3c60704bb7800686f2bd4a0823":{
      "scriptId":"u17"},
    "a18e76e43ea04abbbcd2a66a4f79f124":{
      "scriptId":"u18"},
    "a0b60148a5e7487e9b1789d07597aa43":{
      "scriptId":"u19"},
    "12cfafe919e24a90a84fddbae815dd4e":{
      "scriptId":"u20"},
    "a5e7909ca9614fdfb2a57e007f0e801f":{
      "scriptId":"u21"},
    "9d7072fe9654478fb333308ef6efd0e9":{
      "scriptId":"u22"},
    "11c10cf93c0b4737a5905ccb6cdf10d9":{
      "scriptId":"u23"},
    "0934fe69ffa541d9a354f9fcb0d332fa":{
      "scriptId":"u24"},
    "a8da640193814048bf3e2c036361dcd0":{
      "scriptId":"u25"},
    "8df4f3b4e96046e48803f12fda4d3f00":{
      "scriptId":"u26"},
    "d82180bc216b4db8847a11e857fd0ba2":{
      "scriptId":"u27"},
    "5c56a71d2f5947ae9139577d50fe13d3":{
      "scriptId":"u28"},
    "419402198dec4cc0a88ad79c0e60c877":{
      "scriptId":"u29"},
    "c25634e49ee14a56898692f6bac033f5":{
      "scriptId":"u30"},
    "5cd11d6dfc6e46158f99df73a49dde09":{
      "scriptId":"u31"}}});