$axure.loadCurrentPage({
  "url":"文件对比.html",
  "generationDate":new Date(1462772421707.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7eef755f034b495092e24fbbb1e9c796",
    "type":"Axure:Page",
    "name":"文件对比",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c646a3f9952403c82c27d4594ba2ca8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":14},
            "size":{
              "width":725,
              "height":546}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d84074e3d594d5586a38ab7a17a5539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":14},
                "size":{
                  "width":725,
                  "height":546}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u0.png"}},
{
          "id":"8e384fecb3014e6d9cbb0719ed586686",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":127},
            "size":{
              "width":560,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7172e27064be48f798eaaad4d1a40831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":127},
                "size":{
                  "width":560,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件对比/u2.png"}},
{
          "id":"414e9702521a4eefb6a18cf71d604285",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2E4A58},
            "location":{
              "x":77,
              "y":520},
            "size":{
              "width":703,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f74dce21164de584160f51c89b30af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2E4A58},
                "location":{
                  "x":77,
                  "y":520},
                "size":{
                  "width":703,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件对比/u4.png"}},
{
          "id":"dbb4305727e24bbca44184be1860eeca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00B5FA},
            "location":{
              "x":164,
              "y":73},
            "size":{
              "width":122,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1180af696ac480696a83f589f3e7bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00B5FA},
                "location":{
                  "x":164,
                  "y":73},
                "size":{
                  "width":122,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件兼容/u4.png"}},
{
          "id":"67cc09db4396425180b526b0a9059140",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF15000},
            "location":{
              "x":197,
              "y":463},
            "size":{
              "width":65,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa955539585402abe13f1eba56b73f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF15000},
                "location":{
                  "x":197,
                  "y":463},
                "size":{
                  "width":65,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 6,<br>7,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["d8fd8047dd274448984141a043dfee2c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["179c9ab891514482a33f1464da0bc7a2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8886d0fc3aa04600816644b334ccf598"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ec4bd2d4a1f0433b8b7b706819435b57"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["988e0947fb0247618be0b8c6c31f7252"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/文件对比/u8.png"}},
{
          "id":"131bff9ab5e54917be713994f77bcf00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0042BA},
            "location":{
              "x":365,
              "y":463},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434fc2d8bf7f47b5be25ba2ec89fb7ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0042BA},
                "location":{
                  "x":365,
                  "y":463},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>3,<br>2,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9ce55255a46f461288111e829b1b63de"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9029262b9b3443369fc176cf94223f02"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ad20ea1050547c08b0600632d1cf2ad"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e77cbcb03ad9480cb43126ad9e20ee8e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0e3c20d4eefd40d1a00eb16918c3701c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/文件对比/u10.png"}},
{
          "id":"33b8b04a3ccd40229ca6bdbe08c26ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":447},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265cb8b6c7d041dbb4b1c8cbf8765c23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":447},
                "size":{
                  "width":160,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件上传",
                      "target":{
                        "targetType":"page",
                        "url":"文件上传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ce55255a46f461288111e829b1b63de",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":244,
              "y":176},
            "size":{
              "width":365,
              "height":223},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b803090e68474bb6868b23e8e29d3b6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":244,
                  "y":176},
                "size":{
                  "width":365,
                  "height":223},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u16.png"}},
{
          "id":"9029262b9b3443369fc176cf94223f02",
          "label":"3",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEFF3F6},
            "location":{
              "x":365,
              "y":353},
            "size":{
              "width":135,
              "height":27},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8221a67b42ea471cbf2f4917fc656a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFF3F6},
                "location":{
                  "x":365,
                  "y":353},
                "size":{
                  "width":135,
                  "height":27},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件对比/3_u16.png"}},
{
          "id":"3ad20ea1050547c08b0600632d1cf2ad",
          "label":"2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":260,
              "y":250},
            "size":{
              "width":340,
              "height":80},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8deb7c397f1545598242c4fef4552d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":260,
                  "y":250},
                "size":{
                  "width":340,
                  "height":80},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件对比/2_u18.png"}},
{
          "id":"e77cbcb03ad9480cb43126ad9e20ee8e",
          "label":"4",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":540,
              "y":190},
            "size":{
              "width":50,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0d8189242944c24adcc58f733e5b892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":540,
                  "y":190},
                "size":{
                  "width":50,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>3,<br>2,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9ce55255a46f461288111e829b1b63de"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9029262b9b3443369fc176cf94223f02"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ad20ea1050547c08b0600632d1cf2ad"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e77cbcb03ad9480cb43126ad9e20ee8e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0e3c20d4eefd40d1a00eb16918c3701c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e3c20d4eefd40d1a00eb16918c3701c",
          "label":"5",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":346},
            "size":{
              "width":105,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2e26efc6fed43f6b11706508f23f00a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":346},
                "size":{
                  "width":105,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>3,<br>2,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["9ce55255a46f461288111e829b1b63de"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9029262b9b3443369fc176cf94223f02"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ad20ea1050547c08b0600632d1cf2ad"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e77cbcb03ad9480cb43126ad9e20ee8e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0e3c20d4eefd40d1a00eb16918c3701c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a88f36058fda43b3befc4c2bd19aeed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF504855},
            "location":{
              "x":535,
              "y":463},
            "size":{
              "width":65,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9411c32d615f4350a2a73c439a1a9ccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF504855},
                "location":{
                  "x":535,
                  "y":463},
                "size":{
                  "width":65,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 6,<br>7,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["d8fd8047dd274448984141a043dfee2c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["179c9ab891514482a33f1464da0bc7a2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8886d0fc3aa04600816644b334ccf598"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ec4bd2d4a1f0433b8b7b706819435b57"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["988e0947fb0247618be0b8c6c31f7252"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFunction",
                      "description":"设置 部件文字 7 = &quot;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["24f2a65f79b4419097c6b809690acf7c"]},
{
                                "exprType":"stringLiteral",
                                "value":"  \r\n\r\n                    Are you sure you want to close?",
                                "localVariables":{
},
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/文件对比/u24.png"}},
{
          "id":"d8fd8047dd274448984141a043dfee2c",
          "label":"6",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":244,
              "y":176},
            "size":{
              "width":365,
              "height":223},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48c3ed95873945f389c14be45919d68d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":244,
                  "y":176},
                "size":{
                  "width":365,
                  "height":223},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u16.png"}},
{
          "id":"179c9ab891514482a33f1464da0bc7a2",
          "label":"7",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":262,
              "y":248},
            "size":{
              "width":310,
              "height":81},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f2a65f79b4419097c6b809690acf7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":262,
                  "y":248},
                "size":{
                  "width":310,
                  "height":81},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/2_u18.png"}},
{
          "id":"8886d0fc3aa04600816644b334ccf598",
          "label":"3",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":262,
              "y":349},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40fb46aacf3b4b8f9ed0a3bb6f098755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":262,
                  "y":349},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 6,<br>7,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["d8fd8047dd274448984141a043dfee2c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["179c9ab891514482a33f1464da0bc7a2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8886d0fc3aa04600816644b334ccf598"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ec4bd2d4a1f0433b8b7b706819435b57"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["988e0947fb0247618be0b8c6c31f7252"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec4bd2d4a1f0433b8b7b706819435b57",
          "label":"4",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":394,
              "y":358},
            "size":{
              "width":68,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a4cae53e564856bf5b2bdb53fa21b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":394,
                  "y":358},
                "size":{
                  "width":68,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 6,<br>7,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["d8fd8047dd274448984141a043dfee2c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["179c9ab891514482a33f1464da0bc7a2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8886d0fc3aa04600816644b334ccf598"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ec4bd2d4a1f0433b8b7b706819435b57"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["988e0947fb0247618be0b8c6c31f7252"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988e0947fb0247618be0b8c6c31f7252",
          "label":"5",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":552,
              "y":192},
            "size":{
              "width":50,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a56d3e4cc49c4891b2a63df880df0207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":552,
                  "y":192},
                "size":{
                  "width":50,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 6,<br>7,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["d8fd8047dd274448984141a043dfee2c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["179c9ab891514482a33f1464da0bc7a2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8886d0fc3aa04600816644b334ccf598"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ec4bd2d4a1f0433b8b7b706819435b57"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["988e0947fb0247618be0b8c6c31f7252"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7c646a3f9952403c82c27d4594ba2ca8":{
      "scriptId":"u0"},
    "6d84074e3d594d5586a38ab7a17a5539":{
      "scriptId":"u1"},
    "8e384fecb3014e6d9cbb0719ed586686":{
      "scriptId":"u2"},
    "7172e27064be48f798eaaad4d1a40831":{
      "scriptId":"u3"},
    "414e9702521a4eefb6a18cf71d604285":{
      "scriptId":"u4"},
    "93f74dce21164de584160f51c89b30af":{
      "scriptId":"u5"},
    "dbb4305727e24bbca44184be1860eeca":{
      "scriptId":"u6"},
    "d1180af696ac480696a83f589f3e7bff":{
      "scriptId":"u7"},
    "67cc09db4396425180b526b0a9059140":{
      "scriptId":"u8"},
    "ffa955539585402abe13f1eba56b73f0":{
      "scriptId":"u9"},
    "131bff9ab5e54917be713994f77bcf00":{
      "scriptId":"u10"},
    "434fc2d8bf7f47b5be25ba2ec89fb7ab":{
      "scriptId":"u11"},
    "33b8b04a3ccd40229ca6bdbe08c26ddc":{
      "scriptId":"u12"},
    "265cb8b6c7d041dbb4b1c8cbf8765c23":{
      "scriptId":"u13"},
    "9ce55255a46f461288111e829b1b63de":{
      "scriptId":"u14"},
    "b803090e68474bb6868b23e8e29d3b6d":{
      "scriptId":"u15"},
    "9029262b9b3443369fc176cf94223f02":{
      "scriptId":"u16"},
    "8221a67b42ea471cbf2f4917fc656a2b":{
      "scriptId":"u17"},
    "3ad20ea1050547c08b0600632d1cf2ad":{
      "scriptId":"u18"},
    "8deb7c397f1545598242c4fef4552d08":{
      "scriptId":"u19"},
    "e77cbcb03ad9480cb43126ad9e20ee8e":{
      "scriptId":"u20"},
    "b0d8189242944c24adcc58f733e5b892":{
      "scriptId":"u21"},
    "0e3c20d4eefd40d1a00eb16918c3701c":{
      "scriptId":"u22"},
    "f2e26efc6fed43f6b11706508f23f00a":{
      "scriptId":"u23"},
    "a88f36058fda43b3befc4c2bd19aeed0":{
      "scriptId":"u24"},
    "9411c32d615f4350a2a73c439a1a9ccd":{
      "scriptId":"u25"},
    "d8fd8047dd274448984141a043dfee2c":{
      "scriptId":"u26"},
    "48c3ed95873945f389c14be45919d68d":{
      "scriptId":"u27"},
    "179c9ab891514482a33f1464da0bc7a2":{
      "scriptId":"u28"},
    "24f2a65f79b4419097c6b809690acf7c":{
      "scriptId":"u29"},
    "8886d0fc3aa04600816644b334ccf598":{
      "scriptId":"u30"},
    "40fb46aacf3b4b8f9ed0a3bb6f098755":{
      "scriptId":"u31"},
    "ec4bd2d4a1f0433b8b7b706819435b57":{
      "scriptId":"u32"},
    "61a4cae53e564856bf5b2bdb53fa21b8":{
      "scriptId":"u33"},
    "988e0947fb0247618be0b8c6c31f7252":{
      "scriptId":"u34"},
    "a56d3e4cc49c4891b2a63df880df0207":{
      "scriptId":"u35"}}});