$axure.loadCurrentPage({
  "url":"文件上传.html",
  "generationDate":new Date(1462772421322.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dfd2dd4ae2cc4baeba6a935fbf463c39",
    "type":"Axure:Page",
    "name":"文件上传",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76fc75f865664402baeba449224070da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":21},
            "size":{
              "width":600,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c931682cdc0e4b25bb7f31919c524cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":21},
                "size":{
                  "width":600,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u0.png"}},
{
          "id":"42d31407d07541ceb51773b4984b7aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF264655},
            "location":{
              "x":127,
              "y":510},
            "size":{
              "width":595,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"299c18bc3c3d4dd88ae0358ad5cbb350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF264655},
                "location":{
                  "x":127,
                  "y":510},
                "size":{
                  "width":595,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/u2.png"}},
{
          "id":"40eaaac22a494feea9c4cbb7ffe1f705",
          "label":"1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":183},
            "size":{
              "width":410,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d50c418b0c4a3e876c987adcc0f359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":183},
                "size":{
                  "width":410,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u4.png"}},
{
          "id":"04ef4fd3937d4cfc84c83742b7feece8",
          "label":"2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":320},
            "size":{
              "width":410,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13ed07d2ecb445009958974323b9d24a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":320},
                "size":{
                  "width":410,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/2_u6.png"}},
{
          "id":"e7a4f67b466648f2a0a565004c8da834",
          "label":"upload",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":440},
            "size":{
              "width":130,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af799742ce3c49f08cab3f47f4c01b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":440},
                "size":{
                  "width":130,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2",
                      "objectsToFades":[{
                          "objectPath":["40eaaac22a494feea9c4cbb7ffe1f705"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["04ef4fd3937d4cfc84c83742b7feece8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c5b784e5a1747fdb00ac2cc8bc29aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF504855},
            "location":{
              "x":515,
              "y":453},
            "size":{
              "width":60,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c51ce4afacfc4c93b315d66515ae4925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF504855},
                "location":{
                  "x":515,
                  "y":453},
                "size":{
                  "width":60,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/文件上传/u10.png"}},
{
          "id":"dfb871a95cd4438f9d4160a86470b8c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":186},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c98ae726372462ea39c1f3327f339ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":186},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>2",
                      "objectsToFades":[{
                          "objectPath":["40eaaac22a494feea9c4cbb7ffe1f705"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["04ef4fd3937d4cfc84c83742b7feece8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e4e7e5e3c1c483b873d963e77f0bacf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f31036816845bbaf47c8be76277f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":110,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["2d399719d23e48fc8ade8496bf162b4f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c1b4bda651604d49805178e2f60c9d60"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a94159a615ed4226a62064ff89555119"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ffcece33d9dd4169bd7ef420e51385dd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1e7301b7d3d441f8a2549cc987928536"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d399719d23e48fc8ade8496bf162b4f",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":242,
              "y":167},
            "size":{
              "width":365,
              "height":223},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719fb05b3d3b46719b80f6d848bdec1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":242,
                  "y":167},
                "size":{
                  "width":365,
                  "height":223},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/1_u16.png"}},
{
          "id":"c1b4bda651604d49805178e2f60c9d60",
          "label":"2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":260,
              "y":239},
            "size":{
              "width":310,
              "height":81},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af56619a648e4e0b8498d80eaa69386d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":260,
                  "y":239},
                "size":{
                  "width":310,
                  "height":81},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文件上传/2_u18.png"}},
{
          "id":"a94159a615ed4226a62064ff89555119",
          "label":"3",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":260,
              "y":340},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67f462d9a1940eb959d28c7154fe2e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":260,
                  "y":340},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件兼容",
                      "target":{
                        "targetType":"page",
                        "url":"文件兼容.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffcece33d9dd4169bd7ef420e51385dd",
          "label":"4",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":392,
              "y":349},
            "size":{
              "width":68,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0128a83f719a4dd588f0f884f5b3bd6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":392,
                  "y":349},
                "size":{
                  "width":68,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["2d399719d23e48fc8ade8496bf162b4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c1b4bda651604d49805178e2f60c9d60"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a94159a615ed4226a62064ff89555119"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ffcece33d9dd4169bd7ef420e51385dd"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1e7301b7d3d441f8a2549cc987928536"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e7301b7d3d441f8a2549cc987928536",
          "label":"5",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":550,
              "y":183},
            "size":{
              "width":50,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcabe501805c4bb89044c30af0e3fd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":550,
                  "y":183},
                "size":{
                  "width":50,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 1,<br>2,<br>3,<br>4,<br>5",
                      "objectsToFades":[{
                          "objectPath":["2d399719d23e48fc8ade8496bf162b4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c1b4bda651604d49805178e2f60c9d60"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a94159a615ed4226a62064ff89555119"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ffcece33d9dd4169bd7ef420e51385dd"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1e7301b7d3d441f8a2549cc987928536"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "76fc75f865664402baeba449224070da":{
      "scriptId":"u0"},
    "c931682cdc0e4b25bb7f31919c524cec":{
      "scriptId":"u1"},
    "42d31407d07541ceb51773b4984b7aa8":{
      "scriptId":"u2"},
    "299c18bc3c3d4dd88ae0358ad5cbb350":{
      "scriptId":"u3"},
    "40eaaac22a494feea9c4cbb7ffe1f705":{
      "scriptId":"u4"},
    "95d50c418b0c4a3e876c987adcc0f359":{
      "scriptId":"u5"},
    "04ef4fd3937d4cfc84c83742b7feece8":{
      "scriptId":"u6"},
    "13ed07d2ecb445009958974323b9d24a":{
      "scriptId":"u7"},
    "e7a4f67b466648f2a0a565004c8da834":{
      "scriptId":"u8"},
    "af799742ce3c49f08cab3f47f4c01b55":{
      "scriptId":"u9"},
    "4c5b784e5a1747fdb00ac2cc8bc29aa8":{
      "scriptId":"u10"},
    "c51ce4afacfc4c93b315d66515ae4925":{
      "scriptId":"u11"},
    "dfb871a95cd4438f9d4160a86470b8c2":{
      "scriptId":"u12"},
    "7c98ae726372462ea39c1f3327f339ef":{
      "scriptId":"u13"},
    "4e4e7e5e3c1c483b873d963e77f0bacf":{
      "scriptId":"u14"},
    "35f31036816845bbaf47c8be76277f14":{
      "scriptId":"u15"},
    "2d399719d23e48fc8ade8496bf162b4f":{
      "scriptId":"u16"},
    "719fb05b3d3b46719b80f6d848bdec1c":{
      "scriptId":"u17"},
    "c1b4bda651604d49805178e2f60c9d60":{
      "scriptId":"u18"},
    "af56619a648e4e0b8498d80eaa69386d":{
      "scriptId":"u19"},
    "a94159a615ed4226a62064ff89555119":{
      "scriptId":"u20"},
    "e67f462d9a1940eb959d28c7154fe2e5":{
      "scriptId":"u21"},
    "ffcece33d9dd4169bd7ef420e51385dd":{
      "scriptId":"u22"},
    "0128a83f719a4dd588f0f884f5b3bd6c":{
      "scriptId":"u23"},
    "1e7301b7d3d441f8a2549cc987928536":{
      "scriptId":"u24"},
    "fcabe501805c4bb89044c30af0e3fd53":{
      "scriptId":"u25"}}});